### Получить всех сотрудников
GET http://localhost:8080/employees

### Создать сотрудника 1
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Test1",
  "lastName": "Test1",
  "department": 1,
  "salary": 1000
}

### Создать сотрудника 2
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Test2",
  "lastName": "Test2",
  "department": 3,
  "salary": 5000
}

### Создать сотрудника 3
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Test3",
  "lastName": "Test3",
  "department": 7,
  "salary": 4000
}

### Создать сотрудника 4
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Test4",
  "lastName": "Test4",
  "department": 6,
  "salary": 3000
}

### Создать сотрудника 5
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Test5",
  "lastName": "Test5",
  "department": 9,
  "salary": 2000
}

### Получение суммы зарплат сотрудников
GET http://localhost:8080/employees/salary/sum

### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employees/salary/min

### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employees/salary/max

### Получение всех сотрудников, зарплата которых больше средней зарплаты
GET http://localhost:8080/employees/highSalary